#### values.yaml file for standalone deployment of RStudio Connect ####

# Storage
sharedStorage:
  create: true
  storageClassName: ""
  path: /var/lib/rstudio-connect
  accessModes:
    - ReadWriteOnce
  requests:
    storage: "10Gi"

# Replicas
replicas: 1

# -- Defines the update strategy for a deployment
strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: "100%"


ingress:
  enabled: true
  hosts:
    - host: ralf-connect.k8s.team.soleng.rstudioservices.com
      paths:
          - /

# RStudio Connect configuration
config:
  Python:
    Enabled: true
    Executable:
      - /opt/python/3.9.5/bin/python
  'RPackageRepository "CRAN"':
    URL: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
  'RPackageRepository "RSPM"':
    URL: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
  Server:
    Address: https://ralf-connect.k8s.team.soleng.rstudioservices.com/
    EmailProvider: None
    DefaultContentListView: expanded
  HTTP:
    NoWarning: true
    ForceSecure: true
  Authentication:
    Provider: ldap
  'LDAP "My LDAP Server"':
    ServerAddress: openldap:389
    UserObjectClass: posixAccount
    UserFirstNameAttribute: givenName
    UserLastNameAttribute: sn
    UserEmailAttribute: mail
    UsernameAttribute: cn
    UserSearchBaseDN: dc=example,dc=org
    BindDN: cn=admin,dc=example,dc=org
    GroupObjectClass: posixGroup
    GroupSearchBaseDN: dc=example,dc=org
    GroupNameAttribute: cn
    GroupUniqueIdAttribute: entryUUID
    Logging: true
